### PR TITLE
Make retrieving the subprocess asynchronous

### LINKED ISSUE #43: Retrieve the subprocess asynchronously
We return the subprocess synchronously, as `promise.subprocess`.

https://github.com/sindresorhus/nano-spawn/blob/5f449e1d48925ad87ca39a8afff07f84f6a8ad9f/index.js#L23

https://github.com/sindresorhus/nano-spawn/blob/5f449e1d48925ad87ca39a8afff07f84f6a8ad9f/index.js#L26

https://github.com/sindresorhus/nano-spawn/blob/5f449e1d48925ad87ca39a8afff07f84f6a8ad9f/index.js#L30-L31

That's because `node:child_process` `spawn()` is synchronous. However, in our case, this requires some of our own logic to be synchronous so we can return `promise.subprocess`. This creates the following problems.

### `fs.statSync()` calls

On Windows, we must make `stat` syscalls to know whether the binary requires calling `cmd.exe` or not. We do this twice (since we check two file extensions: `.exe` and `.com`) on every directory of the `PATH`. Due to the above, we must make synchronous calls. That's 20-50 sync `stat` calls done serially.

Being able to make them asynchronously would be much faster, since we could parallelize those calls.

https://github.com/sindresorhus/nano-spawn/blob/5f449e1d48925ad87ca39a8afff07f84f6a8ad9f/windows.js#L34-L41

### Synchronous exceptions

Even though `nanoSpawn()` is async, it can throw sometimes synchronously, which is inconsistent. That's because `node:child_process` `spawn()` throws synchronously when passing some invalid options, e.g. `{uid: -1}` or `{detached: 'should_be_a_boolean'}`.

### Early errors

When running a binary that cannot be found (e.g. due to being misspelled, or not being installed), no subprocess is actually spawned at the OS level. However, Node.js returns an "empty" subprocess instance, which is not very useful. It's also tricky, e.g. its `subprocess.pid` is `undefined`, leading to potential bugs. Node.js then [emits an `error` event](https://github.com/nodejs/node/blob/4a0ec20a35aff521c3a08e42b3905012a6566c00/lib/internal/child_process.js#L404) on the subprocess instance, which leads to `nanoSpawn()` to throw asynchronously.

This situation happens in a couple of other situations, e.g. when spawning too many processes at once, or when hitting OS permissions errors.

Instead of returning a `subprocess` instance which might be "empty", we should wait for the [`spawn` event](https://github.com/nodejs/node/blob/4a0ec20a35aff521c3a08e42b3905012a6566c00/lib/internal/child_process.js#L423) first. That event is actually emitted only one tick later.

### Output iteration + buffering

Due to the above, we need to spawn the subprocess before knowing whether the user wants to iterate its output line-wise. This leads to the problem described in #33.

## Solutions

The `subprocess` instance is useful for a few purposes such as calling `subprocess.kill()` or piping `subprocess.std*`. However, it is meant mostly as an escape hatch, so it's probably ok if it's slightly harder to access.

```js
const promise = nanoSpawn(...);
const subprocess = promise.subprocess;
await promise;
```

We should make retrieving the `subprocess` instance asynchronous. One possible implementation is:

```js
const promise = nanoSpawn(...);
const subprocess = await promise.subprocess();
await promise;
```

Using either callbacks (e.g. an `onStart(subprocess)` option) or events (e.g. a `"start"` event with a `subprocess` payload) is possible too, but harder to use in a promise-based codebase.

If you have any other idea on the specific API, please let me know.

---

What do you think?

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #43.

Trying to keep the code small, although it's hard sometimes! :)

I've named the property `.nodeChildProcess` instead of `.subprocess` following your comment here: https://github.com/sindresorhus/execa/issues/413#issuecomment-2134115941. Also this would allow us to name the main return value `subprocess` instead of `promise` in the documentation, which might be easier to understand. Please let me know if this sounds good.

For example, we could document it along the following lines:

```md
## nanoSpawn(...)

_Returns_: `Subprocess`

## subprocess

_Type_: `Promise<Result>`

### result.stdout

_Type_: `string`

## subprocess[Symbol.asyncIterator]()
## subprocess.stdout
## subprocess.stderr

_Type_: `AsyncIterable<string>`

## subprocess.nodeChildProcess

_Type_: `ChildProcess` (see Node.js doc)
```

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -16,25 +16,51 @@ export default function nanoSpawn(file, commandArguments = [], options = {}) {
...
+		// But it creates an uncaught exception if it happens exactly one tick after 'spawn'.
+		// This prevents that.
+		instance.once('error', () => {});
+
+		await once(instance, 'spawn');
+		return instance;
+	} catch (error) {
+		throw getResultError({
+			error,
+			result: initResult(),
```
Comment (ehmicky) [inline index.js:56]: If the subprocess throws during `spawn()`, we don't have access to the `.stdout` and `.stderr` stream properties. So the only way to know whether `result.stdout`/`result.stderr` should be `undefined` or not is to check whether `spawnOptions.stdout` is either `"pipe"` or `"overlapped"`.

We could do that check, but to save some bytes, this PR is making `result.stdout`/`result.stderr` an empty string instead of `undefined` when using things like `stdout: 'ignore'` or `stdout: 'inherit'`. Also, this could make things a little easier with types. Finally, it could be slightly simpler for users to assume those properties are always strings.

On the other hand, there are some benefits in the `undefined` vs empty string distinction that Execa is making. So I'm not sure whether that's a good idea or not, please let me know what you think.

File: test.js [hunk 2]
```diff
@@ -129,13 +137,13 @@ test('Error on signal termination', async t => {
 	t.is(cause, undefined);
 });
 
-test('Error on invalid child_process options', t => {
-	const {exitCode, signalName, message, cause} = t.throws(() => nanoSpawn('node', ['--version'], {detached: 'true'}));
+test('Error on invalid child_process options', async t => {
+	const {exitCode, signalName, message, cause} = await t.throwsAsync(nanoSpawn('node', ['--version'], {detached: 'true'}));
```
Comment (ehmicky) [inline test.js:141]: This type of errors is now async and has the same shape as the others. :+1:

**Comment by ehmicky** [comment]
Fixed merge conflict.

File: index.js (hunk 1 above)
Comment (sindresorhus) [reply index.js:56]: I think empty strings are the best choice here, and would be for `execa` too.

**Comment by sindresorhus** [comment]
> I've named the property .nodeChildProcess instead of .subprocess following your comment here

I agree. That's a better choice.
